const { createUsersTable } = require('./createUsersTable')
const { createProductSettingsTable } = require('./createProductSettingsTable')
const { createTokensTable } = require('./createTokensTable')
const { createBumpHistoryTable } = require('./createBumpHistoryTable')
const { createSalesHistoryTable } = require('./createSalesHistoryTable')
const { createListingFeesTable } = require('./createListingFeesTable')
const { createActionsHistoryTable } = require('./createActionsHistoryTable')
const { createPartnersTable } = require('./createPartnersTable')
const { createChatSnapshotsTable } = require('./createChatSnapshotsTable')
const { createChatThreadsTable } = require('./createChatThreadsTable')
const { createChatMessagesTable } = require('./createChatMessagesTable')
const { createChatDealsTable } = require('./createChatDealsTable')
const { createChatSyncStateTable } = require('./createChatSyncStateTable')
const { createChatSyncRunsTable } = require('./createChatSyncRunsTable')
const { createPlayerokOutboundIpSettingsTable } = require('./createPlayerokOutboundIpSettingsTable')
const { createApprouteSettingsTable } = require('./createApprouteSettingsTable')
const { createClodeSettingsTable } = require('./createClodeSettingsTable')
const { createUsdRatesTable } = require('./createUsdRatesTable')
const { createTableCodesTable } = require('./createTableCodesTable')
const { createTableTabsTables } = require('./createTableTabsTables')
const { createTableColumnsTables } = require('./createTableColumnsTables')
const { createSentAutomessagesTable } = require('./createSentAutomessagesTable')
const { createSessionsTable } = require('./createSessionsTable')
const { createRobloxAccountsTable } = require('./createRobloxAccountsTable')
const { createMicrosoftAccountsTable } = require('./createMicrosoftAccountsTable')
const { createRobloxOrdersTable } = require('./createRobloxOrdersTable')
const { createSwizzyerSettingsTable } = require('./createSwizzyerSettingsTable')
const { createSwizzyerOrdersTable } = require('./createSwizzyerOrdersTable')

function initDbSchema(db) {
  createUsersTable(db)
  createSessionsTable(db)
  createProductSettingsTable(db)
  createTokensTable(db)
  createBumpHistoryTable(db)
  createSalesHistoryTable(db)
  createListingFeesTable(db)
  createActionsHistoryTable(db)
  createPartnersTable(db)
  createChatSnapshotsTable(db)
  createChatThreadsTable(db)
  createChatMessagesTable(db)
  createChatDealsTable(db)
  createChatSyncStateTable(db)
  createChatSyncRunsTable(db)
  createPlayerokOutboundIpSettingsTable(db)
  createApprouteSettingsTable(db)
  createClodeSettingsTable(db)
  createUsdRatesTable(db)
  createTableCodesTable(db)
  createTableTabsTables(db)
  createTableColumnsTables(db)
  createSentAutomessagesTable(db)
  createRobloxAccountsTable(db)
  createMicrosoftAccountsTable(db)
  createRobloxOrdersTable(db)
  createSwizzyerSettingsTable(db)
  createSwizzyerOrdersTable(db)
}

module.exports = { initDbSchema }

